### ISSUE TITLE
Official bindings

### ISSUE THREAD

**Issue by athre0z** [th0rex/zydis#1]
Hey! Just stumbled across this and wanted to let you know that we'll provide official Rust bindings. In fact, I have them ready on disk, just not committed anywhere yet! Posting here to avoid dev-time being wasted on duplicate work.

**Edit:** If you want to do it anyways, go ahead! Just wanted to let you know. :)

**Comment by athre0z** [comment]
In case you want to have a look ahead of the official binding release, here you go!

[zydis-rs.zip](https://github.com/th0rex/zydis/files/1245317/zydis-rs.zip)

**Comment by athre0z** [comment]
I thought if I posted it here anyway, I might as well create the repo now:
https://github.com/zyantific/zydis-rs

It looks like you have a little more experience with Rust than me. If you want, feel free to drop us issues with things we messed up. 😄

**Comment by th0rex** [comment]
I'm fine with there being official bindings :D I'll just contribute to yours then (since our approaches are pretty much the same with using bindgen anyway).

**Comment by athre0z** [comment]
Very nice! If you're looking for anything to do in particular, the formatter callbacks could need a little bit more "rustiness". They currently take C strings as arguments, requiring users to make their functions unsafe. We should proxify those calls. Also, there are no tests for them, yet.

**Comment by athre0z** [comment]
Also, it'd be cool if we could automatically reexport the constants from the `gen` module to the main module, maybe somehow via `bindgen` config. Or make them enums, then forward the enums. I think I tried the latter half a year ago, however the enums ended up with extremely redundant names (e.g. "`ZydisMachineMode::ZYDIS_MACHINE_MODE_64`). Maybe that's possible to come around now. Any ideas?
